### PR TITLE
SGX upgrade

### PR DESCRIPTION
**Pull request by mbrandenburger**
- Ubuntu 22.04
- SGX SDK 2.22
- SGX SSL 3.0_Rev1
- OpenSSL 3.0.12
- Ego 1.5.0
- Python 3

### CODE REVIEW

**Comment by mbrandenburger** [comment]
@bvavala Can you please test this in HW mode.

**Review by munapower — APPROVED** [review]
Was able to build-dev and start the-simple-test-network

**Review by bvavala — APPROVED** [review]
lg

**Comment by mbrandenburger** [comment]
@munapower this one can be merged once we have #765 approved/merged.

**Pull request merged**
