### PR TITLE
Alternative simulation support for non-sgx platforms

### PR DESCRIPTION
**Pull request by mbrandenburger**
**What this PR does / why we need it**:

This PR introduces an alternative simulation support for non-sgx platforms, such as Mac M1. 
To make this work, both, the FPC chaincode and ercc can be compiled using pure go and without any SGX dependency, which allows playing with your FPC chaincode while developing on your non-sgx host. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing changes and/or breaks backward compatability?**:

```

### CODE REVIEW

**Comment by mbrandenburger** [comment]
@munapower this PR allows me to run FPC go chaincode WITHOUT SGX on Mac M1. Can you please have a look?

**Comment by mbrandenburger** [comment]
Need PR #681 to be merged first

**Review by bvavala — COMMENTED** [review]
looks good

**Comment by Timo-1** [comment]
I tested this PR on a non-Intel and non-Apple platform and the alternative simulation support and the updated instructions work like a charm. They really help when starting to work with FPC.

**Pull request merged**
