### PR TITLE
Update attestation verification with additional quote statuses

### PR DESCRIPTION
**Pull request by bvavala**

### CODE REVIEW

**Comment by mbrandenburger** [comment]
This PR depends on https://github.com/hyperledger-labs/private-data-objects/pull/326

**Comment by bvavala** [comment]
@ikegawa-koshi This PR should make FPC work on Azure with no modifications -- as it handles the `SW_HARDENING_NEEDED` quote status.

**Comment by ikegawa-koshi** [comment]
@bvavala 
Thank you!
I have merged this PR and confirmed that it works correctly in the SGX HW environment in Azure.
If marge this PR, we can try HW mode on Azure from now on, that's super helpful!

**Review by mbrandenburger — APPROVED** [review]
LGTM! Tests run through in HW mode in my dev environment.

**Pull request merged**
