### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by mbrandenburger**
**What this PR does / why we need it**:

This PR fixes remaining issues after the merge of PR #698.
In particular, we ...
- upgrade to go 1.20 and update go dependencies accordingly
- upgrade to Fabric 2.5
- upgrade nanop proto compilier
- fix proto build for the IRB demo
- enable docker build-kit 
- replace marble chaincode with basic asset transfer chaincode from the fabric-samples repository

### CODE REVIEW

**Comment by mbrandenburger** [comment]
@munapower @Flamewind97 can you please have a look. 

@munapower you should be able to test on your m1 mac by setting the following in your `config.override.mk`. 
```
DOCKER_BUILD_CMD=buildx build
DOCKER_BUILD_OPTS=--platform linux/amd64
```

Then run `cd $FPC_PATH && make -C utils/docker build build-dev run-dev` to build the FPC docker images and start the dev container. Within the container you can just run `make` to build and test.

**Review by Flamewind97 — COMMENTED** [review]
Reviewed all file that changes,
no main logic changes except the `ioutil` to `os`.
I have also tested with make build & make test, all works fine.
And also test on the samples hlgf22 and it is working fine in Fabric-smart-client.

**Comment by munapower** [comment]
PR works fine to build dev on an M1 environment. Trying to build the run environments generates errors that seem to be tightly related to the M1 environment and can be addressed in another ticket.
```
make -C _build test || \
	(echo "PDO crypto tests failed. Define PDO_DEBUG_BUILD=1 environment for enabling logging in tests." && exit 1)
make[3]: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
Running tests...
Test project /project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build
    Start 1: utest
1/3 Test #1: utest ............................   Passed    3.29 sec
    Start 2: ttest
2/3 Test #2: ttest ............................***Failed    0.07 sec

    Start 3: attested_evidence_test.sh
3/3 Test #3: attested_evidence_test.sh ........***Failed    1.00 sec
attested_evidence_test.sh: Testing simulated attestation
error creating enclave


33% tests passed, 2 tests failed out of 3

Total Test time (real) =   4.44 sec

The following tests FAILED:
	  2 - ttest (Failed)
	  3 - attested_evidence_test.sh (Failed)
Errors while running CTest
make[3]: *** [Makefile:84: test] Error 8
make[3]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
PDO crypto tests failed. Define PDO_DEBUG_BUILD=1 environment for enabling logging in tests.
make[2]: *** [Makefile:25: test] Error 1
make[2]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto'
make[1]: *** [Makefile:11: test] Error 2
make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/common'
make: *** [Makefile:22: test] Error 2
```
Also for make to run correctly inside the container, before starting it the docker context should be reviewed. In my scenario, even though I had added a DOCKER_HOST variable set to the correct value it was not being used. Instead the context named desktop-linux was being used.
```
docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                               
desktop-linux *     moby                Docker Desktop                            unix:///Users/mariamunaro/.docker/run/docker.sock   
```                      
To change this behaviour I had to issue `docker context use default` for this to change.
```
docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                               
desktop-linux       moby                Docker Desktop                            unix:///Users/mariamunaro/.docker/run/docker.sock        
``` 
From that point forward everything worked correctly for `make clean` and `make build-dev`

**Review by munapower — COMMENTED** [review]
Comment made.

**Comment by mbrandenburger** [comment]
Thanks Maria, I will tackle this docker issue in another PR

**Pull request merged**
